name: Deploy para GitHub Pages com segredo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Criar firebase-config.js a partir do segredo
        run: echo "${{ secrets.FIREBASE_CONFIG }}" > firebase-config.js

      # (Opcional) Se tiveres dependências para compilar ou minificar
      # - name: Instalar dependências
      #   run: npm install

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # ← Publicar a raiz do repositório
